apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-manifests
  namespace: flux
spec:
  interval: 1m
  url: https://github.com/Caesarsage/gitops-manifests
  ref:
    branch: main
